# Generated by Django 5.0.7 on 2024-09-28 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario', '0002_actividad_area_actividad_cambio_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoContinuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(choices=[('Recepción', 'Recepción'), ('Diseño', 'Diseño'), ('Sublimado', 'Sublimado'), ('Confección', 'Confección'), ('Vinilado', 'Vinilado'), ('Bordado', 'Bordado'), ('Embalaje', 'Embalaje')], max_length=100)),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('cantidad_actual', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inventario.producto')),
            ],
        ),
    ]
